config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  # resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :subscriptions, only: [:index]

  get '/users/:id/checkout' => "subscriptions#show", as: 'pay_subs'
  resources :users, controller: "users", only: [:create, :show, :update, :edit] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  # get '/show' => "welcome#show"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/users/:id/add_device" => "devices#new", as: 'devices'
  get "/users/:id/new_subscription" => "subscriptions#new", as: 'new_subscription'

  post '/users/:id' => "users#edit"

  get 'subscriptions/checkout'
  post 'subscriptions/checkout'

  # post "/users/:id/new_subscription" => "subscriptions#checkout"

  post '/users/:id/new_subscription' => "subscriptions#create", as: 'create_subs'


  get '/report' => "dashboard#index", as: 'show_graph'

  get '/report/detail' => "dashboard#show", as: 'show_graph_2'


  # Schedule a new Task
  resources :users, controller: "users", only: [:create, :show, :update, :edit] do
    resources :tasks
    resources :devices
  end
  # post '/users/:id/task/new' => "tasks#create", as: 'create_task'
  delete '/users/:id/task/:id/delete' => "tasks#destroy", as: 'destroy_task'
  get '/users/:id/task/:id/edit' => "tasks#edit", as: 'edit_task'
  post '/users/:id/task/:id/update' => "tasks#update", as: 'update_task'
  # post '/users/:id/new_task' => "tasks#create"
  # get '/task', to: 'ssh_commands#ssh_send', as: 'task'

  # get '/users/:id/checkout' => "subscriptions#show"


  # get '/users/:id' => "subscriptions#show"

  # Cross Origin problem
  match '*all', controller: 'application', action: 'cors_preflight_check', via: [:options]

  mount Sidekiq::Web => '/sidekiq'


end

app/models/task.rb
class Task < ApplicationRecord
  after_save :update_crontab
  after_initialize :end_time
  # validates :name, presence: true

	def turn_on
		puts "model, light on"
	end

  def get_time
    # min_start = min_start ? start_time.strftime("%M") : "nil"
    time_start = start_time ? start_time.strftime("%H:%M:%S") : "nil"
    time_end = end_time ? end_time.strftime("%H:%M:%S") : "nil"
    {end_time: time_end, start_time: time_start}
  end


  private
  def update_crontab
    `cd #{Rails.root} && RAILS_ENV=#{Rails.env} bundle exec whenever --update-crontab`
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	include ApplicationHelper
  # before_action :set_task

  def index
  	# @tasks = Task.all
		@devices = Device.where(user_id: current_user.id)
		@tasks = Task.where(user_id: current_user.id)
  end

  def show
 		@task = Task.find(params[:id])
  end

  def create

    @task = Task.new(task_params)
    @task.user_id = current_user.id
    @task.status = 'Pending'

    if @task.save
    	SshCommand.ssh_new(@task.id)
    	# SshCommand.ssh_new
    	redirect_to user_tasks_path

    else
      redirect_back(fallback_location: root_url)
    end
  end

  def new
  	@task = Task.new
		@devices = Device.where(user_id: current_user.id)
    render template: "tasks/new"
  end

  def edit
  	@task = Task.find(params[:id])
		@task.user_id = current_user.id
		@task.device_id = params[:device_id]
    render template: "tasks/edit"
  end

  def update
  	@task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to user_tasks_path(current_user.id)
      SshCommand.ssh_update(@task.id)
    else
      render '/tasks/new'
    end
  end

  def destroy
		@task = Task.find(params[:id])
    @task.destroy
    SshCommand.ssh_delete(@task.id)
    respond_to do |format|
      format.html { redirect_to user_tasks_path(current_user.id), notice: 'The Task was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def set_task
    @task = Task.find(params[:id])
  end


  def task_params
    params.require(:task).permit(:device_id, :user_id, :description, :start_date, :start_time, :end_date, :end_time)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div id="task-form" class="container">
  <div class="panel">
    <%= form_for(:task, :url => user_tasks_path, :method => :post) do |f| %>
      <div class="row">
        <div class="field">
          <div class="inputs device col-4">
            <label for="">Device</label><br>
            <select name="task[device_id]" id="task_device_id">
              <% @devices.each do |t| %>
              <option value= "<%=t.id%>"><%=Device.find(t.id).name%></option>
              <% end %>
            </select>
          </div>
        </div>
        <div class="field">
          <div class="inputs action col-4">
            <label for="">Action</label><br>
            <%= f.select :description, options_for_select(["Turn on", "Turn off"]), :class => '' %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="field">
          <label>Start date:</label>
          <div class="control">
            <%= date_field_tag 'task[start_date]', nil, :class => 'select task-input' %>
          </div>
        </div>
        <div class="inputs time col-3">
          <label for="">Time</label><br>
          <%= time_field_tag 'task[start_time]', nil, :class => 'select task-input' %>
        </div>
        <div>
          <label>End date:</label>
          <div class="control">
           <%= date_field_tag 'task[end_date]', nil, :class => 'select task-input' %>
          </div>
        </div>
        <div class="inputs time col-3">
          <label for="">Time</label><br>
          <%= time_field_tag 'task[end_time]', nil, :class => 'select task-input' %>
        </div>
      </div>
      <br>
      <div class="row">
        <div id="task-dates-error-notice"><%= flash[:task_error] %></div>
        <br>
        <div class="control">
          <%= f.submit "Add Task", :class => 'button' %>
        </div>
        <p class="form-footer"> (You can edit or delete the task later)</p>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<div id="task-form" class="container">
  <div class="panel">
    <%= form_for(:task, :url => update_task_path, :method => :post) do |f| %>
      <div class="row">
        <div class="field">
          <div class="inputs device col-4">
            <label for="">Device</label><br>
            <select>
              <option>Light</option>
              <option>Other</option>
            </select>
          </div>
        </div>
        <div class="field">
          <div class="inputs action col-4">
            <label for="">Action</label><br>
            <%= f.select :description, options_for_select(["Turn on", "Turn off"]), :class => '' %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="field">
          <label>Start date:</label>
          <div class="control">
            <%= date_field_tag 'task[start_date]', nil, :class => 'select task-input', :value =>@task.start_date %>
          </div>
        </div>
        <div class="inputs time col-3">
          <label for="">Time</label><br>
          <%= time_field_tag 'task[start_time]', nil, :class => 'select task-input', :value =>@task.get_time[:start_time] %>
        </div>
        <div>
          <label>End date:</label>
          <div class="control">
           <%= date_field_tag 'task[end_date]', nil, :class => 'select task-input', :value =>@task.start_date  %>
          </div>
        </div>
        <div class="inputs time col-3">
          <label for="">Time</label><br>
          <%= time_field_tag 'task[end_time]', nil, :class => 'select task-input', :value =>@task.get_time[:end_time]  %>
        </div>
      </div>
      <br>
      <div class="row">
        <div id="task-dates-error-notice"><%= flash[:task_error] %></div>
        <br>
        <div class="control">
          <%= f.submit "Update Task", :class => 'button' %>
        </div>
        <p class="btn-normal"> (You can edit or delete the task later)</p>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<%= stylesheet_link_tag 'tasks' %>
<% if @tasks != nil %>

  <p id="notice"><%= notice %></p>

  <label for=""> Tasks </label>

  <table class="table table-list-search table-striped table-bordered" id="myTable">
    <thead>
      <tr>
        <th>Device</th>
        <th>Description</th>
        <th>Start Date</th>
        <th>Start Time</th>
        <th>End Date</th>
        <th>End Time</th>
        <th colspan="2">Action</th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |t| %>
        <tr>
          <td><%= Device.find(t.device_id).name %></td>
          <td><%= t.description %></td>
          <td><%= t.start_date %></td>
          <td><%= t.get_time[:start_time] %></td>
          <td><%= t.end_date %></td>
          <td><%= t.get_time[:end_time] %></td>
          <td><%= link_to 'Edit', edit_task_path(t) %></td>
          <td><%= link_to 'Delete', destroy_task_path(t), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <%= link_to 'Back', user_devices_path, :class => "btn btn-primary", :id => "model-b" %>

  <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter" id="model-t">
  New Task
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Set your timer</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="column">
          <%= render "/tasks/form" %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

<% else %>
  <h3>Create new task with existing devices</h3>

  <%= render "/tasks/form" %>

  <table class="table table-list-search table-striped table-bordered" id="myTable">
    <thead>
      <tr>
        <td><%= t.device_id %></td>
        <td><%= t.description %></td>
        <td><%= t.start_date %></td>
        <td><%= t.get_time[:start_time] %></td>
        <td><%= t.end_date %></td>
        <td><%= t.get_time[:end_time] %></td>
        <td id="status"><%= t.status %></td>
        <td><%= link_to 'Edit', edit_task_path(t) %></td>
        <td><%= link_to 'Delete', destroy_task_path(t), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <th>Device</th>
        <th>Description</th>
        <th>Start Date</th>
        <th>Start Time</th>
        <th>End Date</th>
        <th>End Time</th>
        <th>Status</th>
        <th colspan="2">Action</th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |t| %>
        <tr>
          <td><%= t.device_id %></td>
          <td><%= t.description %></td>
          <td><%= t.start_date %></td>
          <td><%= t.get_time[:start_time] %></td>
          <td><%= t.end_date %></td>
          <td><%= t.get_time[:end_time] %></td>
          <td><%= t.status %></td>
          <td><%= link_to 'Edit', edit_task_path(t) %></td>
          <td><%= link_to 'Delete', destroy_task_path(t), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<%= link_to 'New Task', new_user_task_path %>

<script type="text/javascript">

  function checkTime(){
    <% @tasks.each do |t| %>
      <% if t.status == 'Pending' %>
        <% if (Time.now.strftime("%d:%m") == t.start_date.strftime("%d:%m")) %>
          <% if (Time.now.strftime("%H:%M") == t.start_time.strftime("%H:%M")) %>
            console.log('completed');
            <% t.update(:status => 'Completed') %>
          <% end %>
        <% end %>
      <% else %>
      <% end %>
    <% end %>
    // t = setTimeout(function() {
    //     checkTime()
    // }, 10000);
  }
  checkTime();

</script>
<% end %>

app/views/tasks/new.html.erb
<!-- <div class="column">
	<%= render "/tasks/form" %>
</div> -->