config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  # resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :subscriptions, only: [:index]

  get '/users/:id/checkout' => "subscriptions#show", as: 'pay_subs'
  resources :users, controller: "users", only: [:create, :show, :update, :edit] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  # get '/show' => "welcome#show"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/users/:id/add_device" => "devices#new", as: 'devices'
  get "/users/:id/new_subscription" => "subscriptions#new", as: 'new_subscription'

  post '/users/:id' => "users#edit"

  get 'subscriptions/checkout'
  post 'subscriptions/checkout'

  # post "/users/:id/new_subscription" => "subscriptions#checkout"

  post '/users/:id/new_subscription' => "subscriptions#create", as: 'create_subs'


  get '/report' => "dashboard#index", as: 'show_graph'

  get '/report/detail' => "dashboard#show", as: 'show_graph_2'


  # Schedule a new Task
  resources :users, controller: "users", only: [:create, :show, :update, :edit] do
    resources :tasks
    resources :devices
  end
  # post '/users/:id/task/new' => "tasks#create", as: 'create_task'
  delete '/users/:id/task/:id/delete' => "tasks#destroy", as: 'destroy_task'
  get '/users/:id/task/:id/edit' => "tasks#edit", as: 'edit_task'
  post '/users/:id/task/:id/update' => "tasks#update", as: 'update_task'
  # post '/users/:id/new_task' => "tasks#create"
  # get '/task', to: 'ssh_commands#ssh_send', as: 'task'

  # get '/users/:id/checkout' => "subscriptions#show"


  # get '/users/:id' => "subscriptions#show"

  # Cross Origin problem
  match '*all', controller: 'application', action: 'cors_preflight_check', via: [:options]

  mount Sidekiq::Web => '/sidekiq'


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		if current_user != nil
			@full_name= current_user.first_name + " " + current_user.last_name
		end
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_signed_in.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">


    <h5 class="display-4">Welcome <%= @full_name %><br>to Dashboard </h5> <br><br><br><h5>



  </div>
  <!-- <h5 class="display-5">To your Dashboard  </h5> -->
</div>
<div class="button-group-1">

  <div class="container">

    <div class="row">
	    	<aside class="col-sm-4">
                <p>Your Device </p>

<div class="card-banner  overlay-grad" style="height:250px; background-image: url('http://bootstrap-ecommerce.com/main/images/posts/1.jpg');">
  <div class="card-body text-white">
    <%= link_to user_devices_path(current_user.id), class:"btn btn-warning btn-sm" do %>
   View More
    <% end %>



    <h5 class="card-title">Check</h5>
    <p class="card-text">List of your device</p>
  </div>
</div> <!-- card.// -->

            </aside>
            <aside class="col-sm-4">
         <p>My Task </p>
<div class="card-banner" style="height:250px; background-image: url('http://bootstrap-ecommerce.com/main/images/posts/2.jpg');">
  <article class="overlay overlay-cover d-flex align-items-center justify-content-center">
    <div class="text-center">
    	<h5 class="card-title">Monitor your device activity</h5>


      <%= link_to user_tasks_path(current_user.id), class:"btn btn-warning btn-sm" do %>
        view more
      <% end %>
    </div>
  </article>
</div> <!-- card.// -->

            </aside>
            <aside class="col-sm-4">
<p>Energy Consumption Report </p>
<div class="card-banner align-items-end" style="height:250px; background-image: url('http://bootstrap-ecommerce.com/main/images/posts/5.jpg');">
	<article class="overlay m-4 w-100">
    	<h5 class="card-title">Analytic and report</h5>

      <%= link_to show_graph_path, class:"btn btn-warning btn-sm" do %>
        View More
      <% end %>
    </article>
</div> <!-- card.// -->

            </aside>
	</div>
</div>


<br><br>
<hr>
<div class="card-body text-center">
<h3 class="text-babu">Add Device </h3>
<p class="text-babu"> Add more features and functions</p>
<p><a href="#"> <%= link_to new_subscription_path(current_user.id), class:"btn btn-warning" do %>
    Add Devices
 <% end %></a>
</div>

app/views/welcome/_signed_out.html.erb
<!-- Full Page Intro -->
 <div class="view full-page-intro">

   <!--Video source-->
   <video class="video-intro" autoplay loop muted>
     <source src="https://mdbootstrap.com/img/video/animation-intro.mp4" type="video/mp4" />
   </video>

   <!-- Mask & flexbox options-->
   <div class="mask rgba-blue-light d-flex justify-content-center align-items-center">

     <!-- Content -->
     <div class="container">

       <!--Grid row-->
       <div class="row d-flex h-100 justify-content-center align-items-center wow fadeIn">

         <!--Grid column-->
         <div class="col-md-6 mb-4 white-text text-center text-md-left">

           <h1 class="display-4 font-weight-bold">Home Automation with SmarTAP</h1>

           <hr class="hr-light">

           <p>
                <strong>Best home automation system in the market</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive lights control system. Deployed all over Malaysia and Asia region. Get the most affordable system now!.</strong>
              </p>

              <a data-toggle="modal" data-target="#at-signup" class="btn btn-outline-white">Sign Up
                       <i class="fa fa-graduation-cap ml-2"></i>
                     </a>
                     <a data-toggle="modal" data-target="#at-login" class="btn btn-outline-white">Sign In
                       <i class="fa fa-download ml-2"></i>
                     </a>

         </div>
         <!--Grid column-->

         <!--Grid column-->
         <div class="col-md-6 col-xl-5 mb-4">

           <img src="https://mdbootstrap.com/img/Mockups/Transparent/Small/admin-new.png" alt="" class="img-fluid">

         </div>
         <!--Grid column-->

       </div>
       <!--Grid row-->

     </div>
     <!-- Content -->

   </div>
   <!-- Mask & flexbox options-->

 </div>
 <!-- Full Page Intro -->

</header>

<!--Main layout-->
<main >
<div class="container">

 <!--Section: Main info-->
 <section class="mt-5 wow fadeIn">

   <!--Grid row-->
   <div class="row">

     <!--Grid column-->
     <div class="col-md-6 mb-4">

       <img src="https://mdbootstrap.com/img/Marketing/mdb-press-pack/mdb-main.jpg" class="img-fluid z-depth-1-half" alt="">

     </div>
     <!--Grid column-->

     <!--Grid column-->
     <div class="col-md-6 mb-4">

       <!-- Main heading -->
       <h3 class="h3 mb-3">Apps to automate your home</h3>
           <p>Your home devices will be controlled via our Web app (
             <strong>SmarTAP</strong> ) Application.</p>
           <p>We revolutionize home automation with simple technology and users frinedly web app.</p>
           <!-- Main heading -->

           <hr>

           <p >
             <strong>FIVE</strong> categories devices control,
             <strong>REPORT</strong> generation and usage analysis,
             <strong>Security</strong> state of the art security control.
             <strong>Easy and fast deployment</strong>
           </p>

     </div>
     <!--Grid column-->

   </div>
   <!--Grid row-->

 </section>
 <!--Section: Main info-->

 <hr class="my-5">

 <!--Section: Main features & Quick Start-->
 <section id="tap">

 </section>
 <section >

   <h3 id="tap" class="h3 text-center mb-5">About SmarTAP</h3>

       <!--Grid row-->
       <div class="row wow fadeIn">

         <!--Grid column-->
         <div class="col-lg-6 col-md-12 px-4">

           <!--First row-->
           <div class="row">
             <div class="col-1 mr-3">
               <i class="fa fa-code fa-2x indigo-text"></i>
             </div>
             <div class="col-10">
               <h5 class="feature-title">SmarTAP 1.0 </h5>
               <p class="grey-text">Utiling Respberry Pi technology we able to deploy affordable home automation system in the region</p>
             </div>
           </div>
       <!--/First row-->

       <div style="height:30px"></div>

       <!--Second row-->
           <div class="row">
             <div class="col-1 mr-3">
               <i class="fa fa-book fa-2x blue-text"></i>
             </div>
             <div class="col-10">
               <h5 class="feature-title">Detailed documentation</h5>
               <p class="grey-text">We give you detailed user-friendly documentation at your disposal. It will help you understand how to troubleshoot our product yourself.
               </p>
             </div>
           </div>
           <!--/Second row-->

           <div style="height:30px"></div>

           <!--Third row-->
           <div class="row">
             <div class="col-1 mr-3">
               <i class="fa fa-graduation-cap fa-2x cyan-text"></i>
             </div>
             <div class="col-10">
               <h5 class="feature-title">Top notch after sales services</h5>
               <p class="grey-text">We care about our users. Our after sales services availave 24/7 to accomodate your need and to assist you at anytime.</p>
             </div>
           </div>
           <!--/Third row-->

     </div>
     <!--/Grid column-->

     <!--Grid column-->
     <div class="col-lg-6 col-md-12">

           <p class="h5 text-center mb-4">What is actually SmarTAP?</p>
           <div class="embed-responsive embed-responsive-16by9">
             <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/My1BDB1ei0E" allowfullscreen></iframe>
           </div>
         </div>
         <!--/Grid column-->

       </div>
       <!--/Grid row-->

     </section>
 <!--Section: Main features & Quick Start-->

 <hr class="my-5">

 <!--Section: Not enough-->
 <section id="team">

   <h3 class="h3 text-center mb-5">Our Awesome Team</h3>
      <div class="team-profile">
          <div class="content-wrap2">
             <%= image_tag("elvis2.jpg", class: "profile-img column-narrow") %>
             <div class="column-wide">
               <h2>Elvis</h2>
               <p>As a developer, I specialize in creating modular and scalable front-end architectures. Love coding</p>
             </div>
         </div>
         <div class="content-wrap2">
            <%= image_tag("asraf2.jpg", class: "profile-img column-narrow") %>
            <div class="column-wide">
              <h2>Asyraf</h2>
              <p>As a developer, I specialize in creating modular and scalable front-end architectures. Love programing</p>
            </div>
        </div>
        <div class="content-wrap2">
           <%= image_tag("fred2.jpg", class: "profile-img column-narrow") %>
           <div class="column-wide">
             <h2>Federico</h2>
             <p>As a developer, I specialize in creating modular and scalable front-end architectures. Likes Back End </p>
           </div>
       </div>
       <div class="content-wrap2">
          <%= image_tag("faiz2.jpg", class: "profile-img column-narrow") %>
          <div class="column-wide">
            <h2>Faiz</h1>
            <p>As a developer, I specialize in creating modular and scalable front-end architectures. He Likes chasing cats in the backyard</p>
          </div>
      </div>
    </div>


 </section>

</div>
</main>

app/views/welcome/index.html.erb
<%= stylesheet_link_tag 'welcome' %>

<% if signed_in? %>

	<%= render partial: '/welcome/signed_in' %>

<% else %>

	<%= render partial: '/welcome/signed_out' %>

<% end %>

app/views/welcome/show.html.erb
show.html.erb