config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  # resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :subscriptions, only: [:index]

  get '/users/:id/checkout' => "subscriptions#show", as: 'pay_subs'
  resources :users, controller: "users", only: [:create, :show, :update, :edit] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  # get '/show' => "welcome#show"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/users/:id/add_device" => "devices#new", as: 'devices'
  get "/users/:id/new_subscription" => "subscriptions#new", as: 'new_subscription'

  post '/users/:id' => "users#edit"

  get 'subscriptions/checkout'
  post 'subscriptions/checkout'

  # post "/users/:id/new_subscription" => "subscriptions#checkout"

  post '/users/:id/new_subscription' => "subscriptions#create", as: 'create_subs'


  get '/report' => "dashboard#index", as: 'show_graph'

  get '/report/detail' => "dashboard#show", as: 'show_graph_2'


  # Schedule a new Task
  resources :users, controller: "users", only: [:create, :show, :update, :edit] do
    resources :tasks
    resources :devices
  end
  # post '/users/:id/task/new' => "tasks#create", as: 'create_task'
  delete '/users/:id/task/:id/delete' => "tasks#destroy", as: 'destroy_task'
  get '/users/:id/task/:id/edit' => "tasks#edit", as: 'edit_task'
  post '/users/:id/task/:id/update' => "tasks#update", as: 'update_task'
  # post '/users/:id/new_task' => "tasks#create"
  # get '/task', to: 'ssh_commands#ssh_send', as: 'task'

  # get '/users/:id/checkout' => "subscriptions#show"


  # get '/users/:id' => "subscriptions#show"

  # Cross Origin problem
  match '*all', controller: 'application', action: 'cors_preflight_check', via: [:options]

  mount Sidekiq::Web => '/sidekiq'


end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :user
	has_many :devices
	before_create :set_balance_unit

	def self.purchase_range
    (1..1)
  end

	def set_balance_unit
		self.balance_unit = self.purchase_unit
	end

  def price
  	@price = '1000'
  end

	def paid
		self.update(payment_verification: true)
	end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController


	def new
		# @subscription = Subscription.all
		@subscription = Subscription.new
		# render 'subscriptions/new'
	end

	def create
		@subscription = Subscription.new(subscription_params)
		@subscription.user_id = current_user.id
		@price = 1000
		@total_cost = @price * @subscription.purchase_unit
		@subscription.update(price: @total_cost)

		if @subscription.save
			session["subs_id"] = @subscription.id
			redirect_to pay_subs_path
		end

	end


	def show
		@client_token = Braintree::ClientToken.generate
		@subscription = Subscription.find(session["subs_id"])
		@total_cost = @subscription.price.to_i * @subscription.purchase_unit
	end

	def checkout
		@subscription = Subscription.find(session["subs_id"])

	  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]
		@unit_price= Subscription.find(session["subs_id"]).price.to_i
		@quantity = Subscription.find(session["subs_id"]).purchase_unit
		@total_cost = @unit_price * @quantity
	  result = Braintree::Transaction.sale(
	   :amount => @total_cost.to_s, #this is currently hardcoded

	   :payment_method_nonce => nonce_from_the_client,
	   :options => {
	      :submit_for_settlement => true
	    }
	   )
	  if result.success?
			@subscription.paid
			@device = Device.new(user_id: current_user.id)
			@device.save
			@device.update(name: "SmartTap #{@device.id}")
			PaymentJob.perform_later(@total_cost, current_user)
	    redirect_to :root, :flash => { :success => "Transaction successful!" }
	  else
	    redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
	  end
	end

	private
		def subscription_params
			params.require(:subscription).permit(:purchase_unit, :price)
		end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= stylesheet_link_tag 'subscriptions' %>
<!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
      Pay now
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Payment for <%=  %></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="demo-frame">

            <%= form_for :checkout_form, url: subscriptions_checkout_path, html: { id: "cardForm"} do |form| %> 

            	<!-- form.select :units, options_for_select([['1 Year @ 199', 199.00],[]]) -->

              <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
              <div id="card-number" class="hosted-field"></div>

              <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
              <div id="expiration-date" class="hosted-field"></div>

              <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
              <div id="cvv" class="hosted-field"></div>

              <%= form.hidden_field "payment_method_nonce" %>
          </div>
          	<div class="button-container">
                <%= form.submit "Make payment", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
            </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
  <script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

  <!-- Load the Hosted Fields component. -->
  <script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

<script>
      var form = document.querySelector('#cardForm');
      var submit = document.querySelector("#submit-payment-btn");
      

      braintree.client.create({
        authorization: '<%= @client_token %>'
      }, function (clientErr, clientInstance) {
        if (clientErr) {
          console.error(clientErr);
          return;
        }

        // This example shows Hosted Fields, but you can also use this
        // client instance to create additional components here, such as
        // PayPal or Data Collector.

        braintree.hostedFields.create({
          client: clientInstance,
          styles: {
            'input': {
              'font-size': '14px'
            },
            'input.invalid': {
              'color': 'red'
            },
            'input.valid': {
              'color': 'green'
            }
          },
          fields: {
            number: {
              selector: '#card-number',
              placeholder: '4111 1111 1111 1111'
            },
            cvv: {
              selector: '#cvv',
              placeholder: '123'
            },
            expirationDate: {
              selector: '#expiration-date',
              placeholder: '10/2019'
            }
          }
        }, function (hostedFieldsErr, hostedFieldsInstance) {
          if (hostedFieldsErr) {
            console.error(hostedFieldsErr);
            return;
          }

          submit.removeAttribute('disabled');

          form.addEventListener('submit', function (event) {
            event.preventDefault();

            hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
              if (tokenizeErr) {
                console.error(tokenizeErr);
                return;
              }

              // If this was a real integration, this is where you would
              // send the nonce to your server.
              document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
              form.submit()
            });

            $( "submit" ).click(function() {
              $( "#flash" ).fadeOut( "slow", function() {
              });
            });
          }, false);
        });
      });
    </script>

app/views/subscriptions/new.html.erb
<!-- include js -->
<!-- <%= javascript_include_tag 'subscriptions', 'data-turbolinks-track': 'reload' %>

<%= form_for @subscription, url: create_subs_path(current_user.id), method: :post, local: true do |f| %>
  <h3>SmartTap's Home Monitoring Device</h3>
  <p>Please play your order</p>
  <table style="width:50%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td>Subscription Fee</td>
    <td>RM1,000</td>
  </tr>
  <tr>
    <td>Warranty</td>
    <td>12 months</td>
  </tr>
  <tr>
    <td>Specification</td>
    <td>
      <ul>
        <li>plug and play easy installation</li>
        <li>light weight</li>
        <li>wifi connectivity</li>
      </ul>
    </td>
  </tr>
</table>


  <p>Quantity: <span onchange= "myFunction()"><%= f.select :purchase_unit, options_for_select([1]), include_blank: false, value: 1 %></span> </p>
  <p id="total_sum"></p>
  <%= f.submit 'Subscribe' %>
<% end -%> -->


<!-- include js -->

<%= javascript_include_tag 'subscriptions', 'data-turbolinks-track': 'reload' %>

<%= form_for @subscription, url: create_subs_path(current_user.id), method: :post, local: true do |f| %>

<table id="tablePreview" class="table table-striped table-borderless">
  <h3>SmartTAP's Home Monitoring Device</h3>
<thread>
  <p>Please play your order</p>
</thread>
  <thead>
    <tr>
      <th>ID</th>
      <th>ITEM</th>
      <th>STATUS</th>

    </tr>
  </thead>


    <tbody>
  <tr>
    <th scope="row">1</th>
    <td>Price per device</td>
    <td>RM1,000</td>
  </tr>
  <tr>
    <th scope="row">2</th>
    <td>Warranty</td>
    <td>12 months</td>
  </tr>
  <tr>
    <th scope="row">3</th>
    <td>Specification</td>
    <td>
      <ul>
        <li>plug and play easy installation</li>
        <li>light weight</li>
        <li>wifi connectivity</li>
      </ul>
    </td>
  </tr>
    </tbody>
</table>
  <p>Quantity: <span onchange= "myFunction()"><%= f.select :purchase_unit, options_for_select(Subscription.purchase_range), include_blank: false %></span> </p>
  <p id="total_sum"></p>
  <%= f.submit 'Subscribe' %>
<% end -%>

app/views/subscriptions/show.html.erb
<div class="container emp-profile">
<h5>Kindly proceed to make payment as per details below:-</h5>
<h5>Purchase Unit: <%= @subscription.purchase_unit %> units </h5>
<h5>Total Due: RM<%= @total_cost %> </h5>
<%= stylesheet_link_tag 'subscriptions' %>
<!-- Button trigger modal -->
    <button type="button" class="btn btn-normal" data-toggle="modal" data-target="#exampleModalCenter">
      Pay now
    </button>
  </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Payment for <%= @subscription.price %></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="demo-frame">

            <%= form_for :checkout_form, url: subscriptions_checkout_path, html: { id: "cardForm"} do |form| %>

            	<!-- form.select :units, options_for_select([['1 Year @ 199', 199.00],[]]) -->

              <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
              <div id="card-number" class="hosted-field"></div>

              <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
              <div id="expiration-date" class="hosted-field"></div>

              <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
              <div id="cvv" class="hosted-field"></div>

              <%= form.hidden_field "payment_method_nonce" %>
          </div>
          	<div class="button-container">
                <%= form.submit "Make payment", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
            </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
  <script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

  <!-- Load the Hosted Fields component. -->
  <script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

<script>
      var form = document.querySelector('#cardForm');
      var submit = document.querySelector("#submit-payment-btn");


      braintree.client.create({
        authorization: '<%= @client_token %>'
      }, function (clientErr, clientInstance) {
        if (clientErr) {
          console.error(clientErr);
          return;
        }

        // This example shows Hosted Fields, but you can also use this
        // client instance to create additional components here, such as
        // PayPal or Data Collector.

        braintree.hostedFields.create({
          client: clientInstance,
          styles: {
            'input': {
              'font-size': '14px'
            },
            'input.invalid': {
              'color': 'red'
            },
            'input.valid': {
              'color': 'green'
            }
          },
          fields: {
            number: {
              selector: '#card-number',
              placeholder: '4111 1111 1111 1111'
            },
            cvv: {
              selector: '#cvv',
              placeholder: '123'
            },
            expirationDate: {
              selector: '#expiration-date',
              placeholder: '10/2019'
            }
          }
        }, function (hostedFieldsErr, hostedFieldsInstance) {
          if (hostedFieldsErr) {
            console.error(hostedFieldsErr);
            return;
          }

          submit.removeAttribute('disabled');

          form.addEventListener('submit', function (event) {
            event.preventDefault();

            hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
              if (tokenizeErr) {
                console.error(tokenizeErr);
                return;
              }

              // If this was a real integration, this is where you would
              // send the nonce to your server.
              document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
              form.submit()
            });

            $( "submit" ).click(function() {
              $( "#flash" ).fadeOut( "slow", function() {
              });
            });
          }, false);
        });
      });
    </script>